### ISSUE TITLE
提个小建议, 是不是没必要有cv_semicircle_color这个属性?

### ISSUE THREAD

**Issue by zty5678** [dongjunkun/CouponView#2]
可以通过给Paint设置setXfermode(new PorterDuffXfermode(PorterDuff.Mode.CLEAR))来实现透明的锯齿?这样cv_semicircle_color就不必存在了

参考:http://stackoverflow.com/questions/18130341/drawing-holes-in-a-canvas
https://gist.github.com/zty5678/f15777ef818c35242105c0f85a9a2d88

**Comment by dongjunkun** [comment]
还是有必要的，一般这个需要和背景设置成一样的，你可以试试其他的背景，反差比较大的

**Comment by dongjunkun** [comment]
好的，我看看

**Comment by dongjunkun** [comment]
试了一下，按照你的方法，锯齿是黑的，不知道是不是打开方式不对

**Comment by zty5678** [comment]
第二个链接里的MyView的运行效果是透明的锯齿。试试让CouponView继承View而不是ViewGroup，且去掉CouponView在xml里的android:background属性？

**Comment by dongjunkun** [comment]
还是留着吧，CouponView是ViewGroup的场景比较多，看了下你的代码， bgColor = Color.parseColor("#ffffff");  mCanvas.drawColor(bgColor); 已经设置成了白色背景了，谢谢你的建议
